variables:
  - group: netlify-group

trigger: ["sprint", "develop", "master"]

# pr:
#   - ["sprint", "develop", "master"]
#
pool:
  vmImage: "Ubuntu-16.04"

steps:
  - task: NodeTool@0
    env:
      BRANCH_NAME: $(Build.SourceBranch)
    inputs:
      versionSpec: "8.x"
    displayName: "Site deploy with $env:BRANCH_NAME"

  - script: npm install -g netlify-cli
    displayName: "Install Netlify"
  - script: cd packages/site && npm install && npm run deploy
    displayName: "Build Site"
  - script: ls && netlify deploy --dir=packages/site/out --auth=$(NETLIFY_AUTH_TOKEN) --site=$env:BRANCH_NAME
    displayName: "Deploy Netlify Site"
